# Generated by Django 6.0.4 on 2026-04-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='from_rag',
            field=models.BooleanField(default=False, help_text='True if response was generated via RAG pipeline'),
        ),
    ]
